name: expense_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # --- UI & Utilities ---
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  uuid: ^4.5.2
  google_fonts: ^6.3.0
  fl_chart: ^0.71.0
  
  # --- Database ---
  sqflite: ^2.4.1
  path_provider: ^2.1.5

  # --- 1. MATA (Kamera & Auto Crop) ---
  # Versi 0.4.0 lebih stabil di environment kamu
  google_mlkit_document_scanner: ^0.4.0  
  google_mlkit_text_recognition: ^0.13.0

  # --- 2. OTAK (Kecerdasan Buatan) ---
  # Ini buat baca teks struknya
  google_generative_ai: ^0.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true